// src/lib/generateMetadata.ts
export function generateMetadata(script: string) {
  const title = script.slice(0, 50) + '...';
  const hashtags = ['#viral', '#ai', '#shorts'];
  const description = `Generated by AI: ${script.slice(0, 100)}...`;

  return { title, description, hashtags };
}
